name: Create Release Pull Request (Version Packages)

on:
  push:
    branches:
      - main

jobs:
  create-release-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
        fetch-depth: 0

    - name: Setup Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm ci

    - name: Create Release Pull Request
      uses: changesets/action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}