name: Publish date-logic

on:
  push:
    tags:
      - '@mpavlovic-txfusion/date-logic@*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup npm # Add our registry to npm config
        run: |
          npm set @mpavlovic-txfusion:registry=https://npm.pkg.github.com/mpavlovic-txfusion
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: Install Dependencies
        run: npm ci

      # - name: Publish
      #   run: |
      #     if [[ ${{ github.ref }} == *"beta"* ]]; then
      #       echo "Publishing package with beta tag"
      #       npm publish @mpavlovic-txfusion/date-logic --tag beta --workspace=packages/date-logic --access=private
      #     else
      #       echo "Publishing package with latest tag"
      #       npm publish @mpavlovic-txfusion/date-logic --tag latest --workspace=packages/date-logic --access=private
      #     fi 

      - name: Get Branch
        run: |
          raw=$(git branch --contains ${{ github.ref }})
          branch=$("$raw" | awk '{print $NF}')
          echo "BRANCH=$branch" >> $GITHUB_ENV

      - name: Create Github Release From Tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "mpavlovic-txfusion"
          git config --global user.email "miroslav@txfusion.io"
          echo ${{ env.BRANCH }}
          if [[ ${{ github.ref }} != *"beta"* ]]; then
            node scripts/create-release-from-tags.js --package date-logic
          else
            echo "Skipping github release creation for beta tag"
          fi

