name: Publish date-logic package

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: choice
        description: package tag
        default: latest
        options: 
          - latest
          - next
          - beta

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup npm # Add our registry to npm config
        run: |
          npm set @mpavlovic-txfusion:registry=https://npm.pkg.github.com/mpavlovic-txfusion
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: Install Dependencies
        run: npm ci

      - name: Publish
        run: npm publish @mpavlovic-txfusion/date-logic --tag ${{ inputs.tag }} --workspace=packages/date-logic --access=private

      - name: Create Git Tag
        run: |
          git config --global user.name "mpavlovic-txfusion"
          git config --global user.email "mirosav@txfusion.io"
          npx changeset tag

      - name: Create Github Release From Tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "mpavlovic-txfusion"
          git config --global user.email "mirosav@txfusion.io"
          node scripts/create-release-from-tags/run.js

