name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
        fetch-depth: 0

    - name: Setup Node.js 14.x
      uses: actions/setup-node@v2
      with: 
        node-version: 14

    - name: Setup npm # Add our registry to npm config
      run: |
        npm set @mpavlovic-txfusion:registry=https://npm.pkg.github.com/mpavlovic-txfusion
        npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

    - name: Install Dependencies
      run: npm ci

    - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}