name: Publish date-logic package

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: choice
        description: package tag
        default: latest
        options: 
          - latest
          - next
          - beta

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup npm # Add our registry to npm config
        run: |
          npm set @mpavlovic-txfusion:registry=https://npm.pkg.github.com/mpavlovic-txfusion
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: Install Dependencies
        run: npm ci

      - name: Publish
        run: npx changeset publish --tag ${{ inputs.tag }}

      - name: Create Github Release From Tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@mpavlovic-txfusion.com"
          git push --follow-tags
          npx ts-node-script --files scripts/create-release-from-tags/run.ts

